### ISSUE TITLE
Follow DOMPurify versioning

### ISSUE THREAD

**Issue by kkomelin** [kkomelin/isomorphic-dompurify#6]
As @NicholasEllul [suggested](https://github.com/kkomelin/isomorphic-dompurify/pull/3#issuecomment-643633694), we could copy DOMPurify versions if [DOMPurify maintainers would agree to use semantic versioning](https://github.com/cure53/DOMPurify/issues/446).

The [idea](https://github.com/kkomelin/isomorphic-dompurify/pull/3#issuecomment-643704217) is to only mirror major and minor versions of DOMPurify. The patch segment would be reserved for our own bug fixes.

**Comment by NicholasEllul** [comment]
Unfortunately it looks like DOMPurify intentionally isn't using semantic versioning meaning that we will just have to do our own thing. I'm not sure how I feel about this, but another idea we had would be to DOMPurify's versioning and add an extra digit on the end for when we need to make bug fixes.

Ex: If DOMPurify is at v2.0.11, we could bump ourselves to v2.0.110. Then if we need to make any bug fixes ourselves we can increment the last digit ex: 2.0.111. It doesn't follow semantic versioning which is why i'm not sure how I feel about it, but would make it easier to for consumers of `isomorphic-dompurify` to know which version of DOMPurify they are using.

**Comment by NicholasEllul** [comment]
I agree with you, its best we keep things simple right now until we really have a good use-case to do otherwise 👍 Good idea getting the smoke test up

**Comment by kkomelin** [comment]
It's always nice to have someone to discuss things with and find an optimal solution together. Thanks for being open for that.
I will then close the issue for now.
